[2020-05-21 16:07:14,142] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-05-21 16:08:08,682] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-all-1-77049ab9-f123-4325-9339-288f8325ead8] in group all has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-05-21 16:08:08,683] INFO [GroupCoordinator 0]: Preparing to rebalance group all in state PreparingRebalance with old generation 5 (__consumer_offsets-23) (reason: removing member consumer-all-1-77049ab9-f123-4325-9339-288f8325ead8 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2020-05-21 16:08:08,683] INFO [GroupCoordinator 0]: Group all with generation 6 is now empty (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2020-05-21 16:08:12,939] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-05-21 16:08:12,943] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-05-21 16:08:12,945] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2020-05-21 16:08:12,958] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-88533-1-1b256faa-4cf1-464e-8638-8173e0c015e4] in group console-consumer-88533 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-05-21 16:08:12,958] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-88533 in state PreparingRebalance with old generation 1 (__consumer_offsets-38) (reason: removing member consumer-console-consumer-88533-1-1b256faa-4cf1-464e-8638-8173e0c015e4 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2020-05-21 16:08:12,958] INFO [GroupCoordinator 0]: Group console-consumer-88533 with generation 2 is now empty (__consumer_offsets-38) (kafka.coordinator.group.GroupCoordinator)
[2020-05-21 16:08:13,265] WARN Session 0x10000a3ce630000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2020-05-21 16:08:13,371] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-05-21 16:08:13,372] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2020-05-21 16:08:14,925] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-05-21 16:08:14,926] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-05-21 16:08:15,027] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-05-21 16:08:16,534] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-05-21 16:08:16,535] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-05-21 16:08:17,775] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-05-21 16:08:17,777] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
